server:
  port: 8080

spring:
  application:
    name: jobportal-springboot-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobportal}
    username: ${SPRING_DATASOURCE_USERNAME:jobportal_user}
    password: ${SPRING_DATASOURCE_PASSWORD:jobportal_pass_2026}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.jobportal: INFO
    org.hibernate.SQL: WARN
